# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
  
  desc "Download metadata from Lokalise"
  lane :lokalise_download do
	lokalise_metadata(
	platform: "android",
    action: "download_from_lokalise",
	release_number: 25,
	)
  end
  
  desc "Upload metadata to Lokalise"
  lane :lokalise_upload do
	lokalise_metadata(
	platform: "android",
    action: "upload_to_lokalise",
    add_languages: true,
    override_translation: true,
	release_number: 25,
	)
  end
  
end
